name: Deploy website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 18
    - name: Install and build
      working-directory: vite-react-monaco
      run: |
        npm ci
        npm run build
    - name: rsync deploy
      uses: Burnett01/rsync-deployments@5.2
      with:
        switches: -avh --delete
        path: vite-react-monaco/dist/
        remote_path: ${{secrets.REMOTE_PATH}}
        remote_host: ${{secrets.REMOTE_HOST}}
        remote_user: ${{secrets.REMOTE_USER}}
        remote_key: ${{secrets.SSH_PRIVATE_KEY}}
        
